### ISSUE TITLE
[SLOVED]Somthing wrong with make the master source code

### ISSUE THREAD

**Issue by SvenAugustus** [nm-l2tp/network-manager-l2tp#105]
src/nm-l2tp-pppd-plugin.c:353:2: 错误：‘eaptls_passwd_hook’ undeclared (first use in this function); did you mean ‘pap_passwd_hook’?
  eaptls_passwd_hook = get_credentials;
  ^~~~~~~~~~~~~~~~~~

**Comment by dkosovic** [comment]
As mentioned in the [README.md](https://github.com/nm-l2tp/network-manager-l2tp/blob/master/README.md) file, the `ppp` package has to have the EAP-TLS patch for pppd applied to its source code (which most Linux distributions already do), see :

* https://www.nikhef.nl/~janjust/ppp/

**Comment by SvenAugustus** [comment]
> As mentioned in the [README.md](https://github.com/nm-l2tp/network-manager-l2tp/blob/master/README.md) file, the `ppp` package has to have the EAP-TLS patch for pppd applied to its source code (which most Linux distributions already do), see :
> 
>     * https://www.nikhef.nl/~janjust/ppp/

thks, now i reset to commit id back to Dec 2, 2018. it works well.

**Comment by dkosovic** [comment]
You might be better to use the nm-1-2 branch, I'll will be releasing a new 1.2.12 version from that branch in the next couple of weeks.

The master branch is mainly for those that want to use user or machine certificates. The certificate support was fixed in December. Because of GPL v2 licensing incompatibilty issues, I have to wait till OpenSSL 3.0 is released which is compatible with GPL v2 license before I can make a release from the master branch available for linux distributions.

I'll close this issue.
