### ISSUE TITLE
can't find libnma-dev libnm-dev on ubuntu 14.04 anyone is able to run on it?

### ISSUE THREAD

**Issue by greenSnot** [nm-l2tp/network-manager-l2tp#30]

**Comment by dkosovic** [comment]
With Ubuntu 14.04 you need to use the _nm-1-0_ branch of this repository. Unfortunately due to issue https://github.com/nm-l2tp/network-manager-l2tp/issues/28 you currently need to use version 1.0.4 which is the latest stable release from  _nm-1-0_ branch of this repository by issuing the following : 

    git checkout 1.0.4

_libnma-dev_ was introduced with Ubuntu 16.04 so can be ignored. I don't have access to Ubuntu 14.04, but I'm guessing _libnm-dev_ was called _network-manager-dev_

**Comment by dkosovic** [comment]
The latest checkout of the _nm-1-0_ branch from this repository now builds on Debian 8, so should also build on Ubuntu 14.04.

**Comment by dkosovic** [comment]
I was wrong that the _nm-1-0_ branch would build on Ubuntu 14.04, sorry about that.

I had someone at work who was using Ubuntu 14.04, so I decided to look into it, Ubuntu 14.04 is older than Debian 8 and is missing some of the NetworkManager APIs, it also needs different `./configure` arguments as its x86-64 NetworkManager package wasn't Multiarch yet.

As of commit #https://github.com/nm-l2tp/network-manager-l2tp/commit/2cc1484ac9e3db776b5913166bff647500f03320 the _nm-1-0_ branch and network-manager-l2tp 1.08 are now compatible with Ubuntu 14.04.

There is also a network-manager-l2tp 1.0.8 PPA package on:
* https://launchpad.net/~nm-l2tp/+archive/ubuntu/network-manager-l2tp

Although Sergey Prokhorov had previously released network-manager-l2tp 0.9.8.5 PPA for Ubuntu 14.04, I wasn't able to get it to work with my workplace L2TP/IPsec server.
