### ISSUE TITLE
l2tp settings missing advanced settings on KDE 5 

### ISSUE THREAD

**Issue by Deckee** [nm-l2tp/network-manager-l2tp#61]
KDE 5 mint 18.2
![image](https://user-images.githubusercontent.com/8199121/29665174-9ac16598-8898-11e7-968e-dacbe482db44.png)
lubuntu 17.04
![20170824_063529](https://user-images.githubusercontent.com/8199121/29665240-d30cb66e-8898-11e7-9963-92a99e34e344.jpg)

Device: Dell N5050
Boot:dosmbr
Cputype:x86_64
Cpu:2350m

**Comment by dkosovic** [comment]
See the KDE Plasma < 5.11 and legacy IPsec IKEv1 ciphers section in the Wiki :
* https://github.com/nm-l2tp/network-manager-l2tp/wiki/Known-Issues#kde-plasma--511-and-legacy-ipsec-ikev1-ciphers

Another workaround is to replace strongswan with libreswan which generally doesn't need the Phase 1 and Phase 2 algorithms to be set, by issuing the following:

```
sudo apt install libreswan
```

**Comment by Deckee** [comment]
That didn't fix the issue, I never had strongswan or openswan, but kde thinks they are there but they are not, I'm using mint kde 18.2. The kde 5.11 update will take a while I'm on kde 5.8.7, a temporary fix would be making you own window that would be open form bash to configure the cyphers.

**Comment by dkosovic** [comment]
If I'm not mistaken, Mint 18.2 is a derivative of Ubuntu 16.04.2 LTS. Are you using the PPA packages with Linux Mint?
* https://launchpad.net/%7Enm-l2tp/+archive/ubuntu/network-manager-l2tp

The PPA network-manager-l2tp package has a dependency on strongswan or libreswan. I backported libreswan from Ubuntu 17.04 and made it available for 16.04 in that same PPA repository.

With libreswan you do not need to add 3des-sha1-mod1024 and 3des-sha1 in the advanced section like you do with strongswan.

I don't understand what didn't work?  using`/usr/bin/nm-connection-editor` to edit the connection or installing libreswan? I never mentioned openswan and network-manager-l2tp isn't compatible with it anyway.

It is possible submit a Mint KDE Plasma bug and request that the patch be backported to Plasma 5.8.7 package. It should apply cleanly as the code hasn't changed in a while.

NetworkManager has had a command-line interface since version 1.2.0, you can use it to edit VPN connections. But I still think installing libreswan is the simplest option.

**Comment by Deckee** [comment]
I will just wait for the mint kde team to push the new kde at the end of the year. I will use tor for the time being, and use a custom dns to get around the blocking on the network i use my vpn on.
