### ISSUE TITLE
Don't require a password when authentication with certificates

### ISSUE THREAD

**Issue by frenetic1** [nm-l2tp/network-manager-l2tp#7]
Hi,

can you apply this patch:
https://github.com/seriyps/NetworkManager-l2tp/issues/44

thx

**Comment by dkosovic** [comment]
I've applied patch to the nm-1-0 branch.

Unfortunately for the master branch, the code has changed considerably after commit https://github.com/nm-l2tp/network-manager-l2tp/commit/66a5355c971a77aaa7b06540025521084116609a which used NetworkManager-pptp 1.2.2's nm-pptp-service code and retrofitted the L2TP/IPSec code.  The certificate code hadn't been retrofitted due to the considerable number of changes and I wasn't able to test.

**Comment by frenetic1** [comment]
Thanks!
Maybe I try to take a look at it in the next weeks. Do you already know which change causes a lot of work on retrofitting the cert code?

**Comment by dkosovic** [comment]
It's not so much about causing a lot of work to retrofit, but needing to be able to test. Lots of code has moved around and some of the credential handling code has changed or been removed, so if I added the cert code myself, chance are it would be broken as I'm not able to test. 

note: nm-1-0 branch is intended for NetworkManger 1.0 (and 0.9) based linux distributions, while the master brand is for NetworkManger 1.2 (and 1.1) based linux distributions.

The Plasma-nm l2tp front-end may also need some changes to work due to minor DBus interface changes to the backed-end, but as the changes are based on the recent NetworkManager-pptp changes, they should be similar to any Plasma-nm pptp front-end changes if it has any.

**Comment by dkosovic** [comment]
I'm closing this issue for the time being.

There has since been a new release (version 1.2.4).

If you wish to re-open, reply with any changes.
